name: firebase_core_desktop
description: Desktop implementation of firebase_core
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.2

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: '>=1.20.0'

dependencies:
  firebase_core_dart: ^1.0.1
  firebase_core_platform_interface: ^4.5.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  firebase_core: ^2.0.10
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  plugin_platform_interface: ^2.1.4

flutter:
  plugin:
    implements: firebase_core
    platforms:
      macos:
        dartPluginClass: FirebaseCore
        pluginClass: none
      linux:
        dartPluginClass: FirebaseCore
        pluginClass: none
      windows:
        dartPluginClass: FirebaseCore
        pluginClass: none

false_secrets:
  - /example/lib/main.dart
