name: firebase_auth_desktop
description: Windows and Linux implementation of firebase_auth
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 1.0.2

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: '>=1.20.0'

dependencies:
  desktop_webview_auth: ^0.0.11
  firebase_auth: ^4.4.2
  firebase_auth_dart: ^1.0.1
  firebase_auth_platform_interface: ^6.5.2
  firebase_core: ^2.10.0
  firebase_core_dart: ^1.0.1
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  async: ^2.10.0
  firebase_core_platform_interface: ^4.5.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  plugin_platform_interface: ^2.1.4

flutter:
  plugin:
    implements: firebase_auth
    platforms:
      macos:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none
      linux:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none
      windows:
        dartPluginClass: FirebaseAuthDesktop
        pluginClass: none

false_secrets:
  - /example/**
